./" *************************************************************************
./"     gwm.1：gwm(1)手冊頁。
./"     版權 (C) 2020 gsm <406643764@qq.com>
./"     本程序為自由軟件：你可以依據自由軟件基金會所發布的第三版或更高版本的
./" GNU通用公共許可證重新發布、修改本程序。
./"     雖然基于使用目的而發布本程序，但不負任何擔保責任，亦不包含適銷性或特
./" 定目標之適用性的暗示性擔保。詳見GNU通用公共許可證。
./"     你應該已經收到一份附隨此程序的GNU通用公共許可證副本。否則，請參閱
./" <http://www.gnu.org/licenses/>。
./" ************************************************************************/
.TH gwm 1 2021年3月 "gwm 0.8.7" gwm
.
.SH 名稱
gwm \- gwm（gsm's window manager），是一個X11動態窗口管理器。
.
.SH 摘要
.B gwm
.
.SH 描述
gwm（gsm's window manager），是一個X11動態窗口管理器。
gwm支持全屏、平鋪、堆疊、預覽四種基本窗口布局模式和懸浮模式這一種特殊的窗口布局模式，以及基本模式與懸浮模式的混合。這些模式是動態切換或混合的。當然，也可以用命令切換布局模式。
以下所說的窗口，除非特別說明，否則均指受本窗口管理器所管理的窗口。
全屏模式是當前窗口獨佔整個屏幕空間的布局模式。
平鋪模式是所有窗口按堆疊次序分配除狀態欄之外的所有屏幕空間的布局模式。它把屏幕空間劃分爲主區域、次區域、固定區域、狀態欄。若固定區域沒有窗口佔用，則該區域並入主區域和次區域。三個區域各自均勻分配空間給相應的窗口。
堆疊模式是窗口之間可以堆疊、所有窗口按原來的位置排列並佔用除狀態欄之外的所有屏幕空間的布局模式。
預覽模式是所有窗口平均分配除狀態欄之外的所有屏幕空間的布局模式。
懸浮模式是懸浮類型的窗口堆疊在其他類型的窗口之上的布局模式。
.
.SH 選項
無。
.
.SH 用法
.
.SS 通用說明
.
.TP
可以通過xmodmap(1)查看功能轉換鍵的映射，通常Mod1對應Alt、Mod4對應Super。一般情況下，若存在懸浮窗口，則懸浮窗口之間的堆疊次序保持不變，堆疊在其他類型的窗口上邊；以下除非特別說明，否則均爲以上情況。窗口堆疊次序是指窗口之前的放置次序，默認爲窗口打開的先後次序，先打開的窗口在堆棧的下面，後打開的窗口在堆棧的上邊，即後進先出；窗口管理器可以改變窗口疊次序。在平鋪模式下移動窗口或調整窗口大小，會使該窗口處於懸浮模式，而其餘窗口保持原來的布局模式。定位器點擊窗口會將該窗口切換爲當前窗口，也就是說，若該窗口爲懸浮窗口，則將該窗口提升到窗口疊頂部，否則，將該窗口提升至除懸浮窗口之外的所有窗口之上，並且獲得鍵盤輸入焦點。僅能在堆疊、平鋪模式下移動窗口或調整窗口尺寸。對於窗口疊次序，懸浮窗口總是在狀態欄之上，其他類型的窗口總是在狀態欄之下。
.TP
狀態欄會顯示"xsetroot \-name"的結果。
.
.SS 鍵盤命令
.
.TP
.B Mod1+Mod4+t
打開lxterminal(1)模擬終端。
.
.B Mod1+Mod4+f
打開默認的文件瀏覽器。
.
.TP
.B Mod1+Mod4+w
通過執行"xwininfo -wm > log"命令來取得窗口管理器提示信息。
.
.TP
.B Mod1+Mod4+p
打開dmenu_run。可用它來運行其他程序。
.
.TP
.B Mod1+Mod4+q
打開QQ。
.
.TP
.B Mod1+Mod4+s
打開星際譯王。
.
.TP
.B Mod4+Up
向上移動當前窗口。
.
.TP
.B Mod4+Down
向下移動當前窗口。
.
.TP
.B Mod4+Left
向左移動當前窗口。
.
.TP
.B Mod4+Right
向右移動當前窗口。
.
.TP
.B Mod4+[
向上移動當前窗口上邊界。
.
.TP
.B Mod4+]
向下移動當前窗口上邊界。
.
.TP
.B Mod4+;
向上移動當前窗口下邊界。
.
.TP
.B Mod4+'
向下移動當前窗口下邊界。
.
.TP
.B Mod4+9
向左移動當前窗口左邊界。
.
.TP
.B Mod4+0
向右移動當前窗口左邊界。
.
.TP
.B Mod4+-
向左移動當前窗口右邊界。
.
.TP
.B Mod4+=
向右移動當前窗口右邊界。
.
.TP
.B Mod4+Delete
退出gwm。如果通過startgwm啓動gwm的話，應當使用pkill -9 startgwm退出。
.
.TP
.B Mod4+c
關閉窗口。
.
.TP
.B Mod4+Tab
切換到下一個窗口。
.
.TP
.B Mod4+f
切換到全屏模式。
.
.TP
.B Mod4+g
切換到預覽模式。
.
.TP
.B Mod4+s
切換到堆疊模式。
.
.TP
.B Mod4+t
切換到平鋪模式。
.
.TP
.B Mod4+i
增加主區域可容納窗口的數量。
.
.TP
.B Mod4+Shift+i
減少主區域可容納窗口的數量。
.
.TP
.B Mod4+m
如果存在次區域，則增加主區域比例，並相應地減小次區域比例。
.
.TP
.B Mod4+Shift+m
如果存在次區域，則減少主區域比例，並相應地增加次區域比例。
.TP
.B Mod4+F1
在平鋪模式下，把當前窗口移動至主區域的頂部。
.
.TP
.B Mod4+F2
在平鋪模式下，把當前窗口移動至次區域的頂部。如果主區域窗口數小於主區域可容納窗口數，或者主區域窗口數等於主區域可容納窗口數且當前窗口位於主區域，則不執行任何操作。
.
.TP
.B Mod4+F3
在平鋪模式下，把當前窗口移動至固定區域的頂部。
.
.TP
.B Mod4+F4
在任何模式下，把當前窗口切換爲懸浮狀態。
.
.SS 定位器命令
.TP
.B Mod4+定位器按鈕1
若按着Mod4+定位器按鈕1（通常是鼠標左鍵）不放並移動定位器，則移動定位器按鈕1所點擊的窗口。若按着Mod4+定位器按鈕1且不移動定位器，則僅僅切換窗口。
.
.TP
.B Mod4+定位器按鈕3
若按着Mod4+定位器按鈕3（通常是鼠標右鍵）不放並移動定位器，則調整定位器按鈕3所點擊的窗口的尺寸。若按着Mod4+定位器按鈕3且不移動定位器，則僅僅切換窗口。當定位器按鈕3點擊窗口對角線附近區域時，可雙向調整窗口尺寸，否則只能單向調整。
.
.TP
.B Mod4+Shift+定位器按鈕1
若按着Mod4+Shift+定位器按鈕1（通常是鼠標左鍵）不放並移動定位器，則移動定位器按鈕1所點擊的窗口，當釋放定位器按鈕1時，該窗口移動至該位置。若按着Mod4+Shift+定位器按鈕1且不移動定位器，則僅僅切換窗口。
.
.SS 配置
.
.TP
目前只能通過修改源代碼來修改配置。
.
.SH 漏洞報告
.
若你發現漏洞，則請向<406643764@qq.com>報告。
.
.SH 作者
.
此程序由gsm<406643764@qq.com>開發。
.br
官方網站：https://sourceforge.net/projects/gsmwm/。
.
.SH 版權
.
版權 \(co 2020 gsm <406643764@qq.com>。
.br
本程序為自由軟件：你可以依據自由軟件基金會所發布的第三版或更高版本的GNU通用公共許可證重新發布、修改本程序。
