./" *************************************************************************
./"     gwm.1：gwm(1)手冊頁。
./"     版權 (C) 2020 gsm <406643764@qq.com>
./"     本程序為自由軟件：你可以依據自由軟件基金會所發布的第三版或更高版本的
./" GNU通用公共許可證重新發布、修改本程序。
./"     雖然基于使用目的而發布本程序，但不負任何擔保責任，亦不包含適銷性或特
./" 定目標之適用性的暗示性擔保。詳見GNU通用公共許可證。
./"     你應該已經收到一份附隨此程序的GNU通用公共許可證副本。否則，請參閱
./" <http://www.gnu.org/licenses/>。
./" ************************************************************************/
.TH gwm 1 2020年5月 "gwm 0.5" gwm
.
.SH 名稱
gwm \- gsm（gsm's window manager），是一個X11動態窗口管理器。
.
.SH 摘要
.B gwm
.
.SH 描述
gsm（gsm's window manager），是一個X11動態窗口管理器。
gwm支持全屏、平鋪、堆疊三種基本窗口布局模式，以及懸浮模式與以上三種模式的混合。這些模式是動態切換或混合的。當然，也可以用命令切換布局模式。
.
.SH 選項
無。
.
.SH 用法
.
.SS 通用說明
.
.TP
可以通過xmodmap(1)查看功能轉換鍵的映射，通常Mod1對應Alt、Mod4對應Super。以下所說的窗口，除非特別說明，否則均指受本窗口管理器所管理的窗口。一般情況下，若存在懸浮窗口，則懸浮窗口之間的堆疊次序保持不變，並堆疊在其餘窗口上邊；以下除非特別說明，否則均爲以上情況。窗口堆疊次序是指窗口打開的先後次序，先打開的窗口在堆棧的下面，後打開的窗口在堆棧的上邊，即後進先出。在全屏、平鋪模式下移動窗口或調整窗口大小，都會使該窗口處於懸浮模式，而其餘窗口保持原來的布局模式。移動窗口或調整窗口大小，都會將該窗口切換爲當前窗口，即將該窗口提升到堆棧頂部，並獲得鍵盤聚焦。
.TP
狀態欄會顯示"xset \-name"的結果。
.
.SS 鍵盤命令
.
.TP
.B Mod1+Mod4+t
打開lxterminal(1)模擬終端。
.
.TP
.B Mod1+Mod4+w
通過執行"xwininfo -wm > log"命令來取得窗口管理器提示信息。
.
.TP
.B Mod1+Mod4+p
打開dmenu_run。可用它來運行其他程序。
.
.TP
.B Mod4+Up
向上移動當前窗口。
.
.TP
.B Mod4+Down
向下移動當前窗口。
.
.TP
.B Mod4+Left
向左移動當前窗口。
.
.TP
.B Mod4+Right
向右移動當前窗口。
.
.TP
.B Mod4+[
向上移動當前窗口上邊界。
.
.TP
.B Mod4+]
向下移動當前窗口上邊界。
.
.TP
.B Mod4+;
向上移動當前窗口下邊界。
.
.TP
.B Mod4+'
向下移動當前窗口下邊界。
.
.TP
.B Mod4+9
向左移動當前窗口左邊界。
.
.TP
.B Mod4+0
向右移動當前窗口左邊界。
.
.TP
.B Mod4+-
向左移動當前窗口右邊界。
.
.TP
.B Mod4+=
向右移動當前窗口右邊界。
.
.TP
.B Mod4+Delete
退出gwm。如果通過startgwm啓動gwm的話，應當使用pkill -9 startgwm退出。
.
.TP
.B Mod4+c
關閉窗口。
.
.TP
.B Mod4+Tab
切換到下一個窗口。
.
.TP
.B Mod4+\[rs]
切換當前窗口的懸浮狀態。即：若當前窗口爲懸浮狀態，則切換爲非懸浮狀態；若當前窗口爲非懸浮狀態，則切換爲懸浮狀態。
.
.TP
.B Mod4+f
切換到全屏模式。若當前窗口不是懸浮窗口，則該模式將屏幕空間全部分配給當前窗口；否則將屏幕空間全部分配給所有非懸浮窗口之中的最近打開的窗口。
.
.TP
.B Mod4+g
切換到格子模式。該模式將屏幕空間平均分配給所有可見窗口，比較適合於預覽。
.
.TP
.B Mod4+s
切換到堆疊模式。該模式按窗口堆疊次序和固定的縮進依次堆疊，上邊的窗口會遮擋下面的窗口的一部分。
.
.SS 鍵盤命令
.TP
暫無。
.
.SS 配置
.
.TP
目前只能通過修改源代碼來修改配置。
.
.SH 漏洞報告
.
若你發現漏洞，則請向<406643764@qq.com>報告。
.
.SH 作者
.
此程序由gsm<406643764@qq.com>開發。
.br
官方網站：https://sourceforge.net/projects/gsmwm/。
.
.SH 版權
.
版權 \(co 2020 gsm <406643764@qq.com>。
.br
本程序為自由軟件：你可以依據自由軟件基金會所發布的第三版或更高版本的GNU通用公共許可證重新發布、修改本程序。
