#!/bin/sh

[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources &
xsetroot -solid black &

export LC_ALL="zh_CN.UTF-8"
#export XMODIFIERS='@im=fcitx'
#export GTK_IM_MODULE=fcitx
#export QT_IM_MODULE=fcitx
#fcitx > /dev/null 2>&1 &

while true
do
    VOL=$(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/音\1/')
    LOCALTIME=$(date "+%m/%d %a %p%H:%M")
    if acpi -a | grep off-line > /dev/null
    then
        BAT="电$(acpi -b | awk '{ print $4 " " $5 }' | tr -d ',')"
        xsetroot -name " $BAT $VOL $LOCALTIME"
    else
        xsetroot -name " $VOL $LOCALTIME"
    fi
    sleep 10s
done &

while true
do
    gwm
done
